/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoriesSlugRouteImport } from './routes/stories/$slug'
import { Route as ApiUserStatsRouteImport } from './routes/api/user-stats'
import { Route as ApiTrendingRouteImport } from './routes/api/trending'
import { Route as ApiThemesRouteImport } from './routes/api/themes'
import { Route as ApiSubmissionsRouteImport } from './routes/api/submissions'
import { Route as ApiStoriesCatalogueDataRouteImport } from './routes/api/stories-catalogue-data'
import { Route as ApiStoriesCatalogueRouteImport } from './routes/api/stories-catalogue'
import { Route as ApiStoriesRouteImport } from './routes/api/stories'
import { Route as ApiStatesRouteImport } from './routes/api/states'
import { Route as ApiReadingProgressRouteImport } from './routes/api/reading-progress'
import { Route as ApiLikesRouteImport } from './routes/api/likes'
import { Route as ApiLatestStoriesRouteImport } from './routes/api/latest-stories'
import { Route as ApiHeroSlidesRouteImport } from './routes/api/hero-slides'
import { Route as ApiHeroOfTheDayRouteImport } from './routes/api/hero-of-the-day'
import { Route as ApiFeaturedRouteImport } from './routes/api/featured'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiBookmarksRouteImport } from './routes/api/bookmarks'
import { Route as ApiAuthorsRouteImport } from './routes/api/authors'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminAchievementsRouteImport } from './routes/admin/achievements'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminStoriesIndexRouteImport } from './routes/admin/stories/index'
import { Route as AdminStatesIndexRouteImport } from './routes/admin/states/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminCommunityIndexRouteImport } from './routes/admin/community/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminAuthorsIndexRouteImport } from './routes/admin/authors/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as ApiUserStatsMeRouteImport } from './routes/api/user-stats/me'
import { Route as ApiStoriesSearchRouteImport } from './routes/api/stories/search'
import { Route as ApiStoriesRecommendedRouteImport } from './routes/api/stories/recommended'
import { Route as ApiStoriesLatestRouteImport } from './routes/api/stories/latest'
import { Route as ApiStoriesFilterRouteImport } from './routes/api/stories/filter'
import { Route as ApiStoriesFeaturedRouteImport } from './routes/api/stories/featured'
import { Route as ApiStoriesSlugRouteImport } from './routes/api/stories/$slug'
import { Route as ApiCommentsReportRouteImport } from './routes/api/comments/report'
import { Route as ApiCommentsLikeRouteImport } from './routes/api/comments/like'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminSubmissionsRouteImport } from './routes/api/admin/submissions'
import { Route as ApiAdminStoriesRouteImport } from './routes/api/admin/stories'
import { Route as ApiAdminStatesRouteImport } from './routes/api/admin/states'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminMediaRouteImport } from './routes/api/admin/media'
import { Route as ApiAdminCommentsRouteImport } from './routes/api/admin/comments'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api/admin/categories'
import { Route as ApiAdminAuthorsRouteImport } from './routes/api/admin/authors'
import { Route as ApiAdminAnalyticsRouteImport } from './routes/api/admin/analytics'
import { Route as ApiAdminAchievementsRouteImport } from './routes/api/admin/achievements'
import { Route as AdminStoriesNewRouteImport } from './routes/admin/stories/new'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users.$id'
import { Route as ApiAdminSubmissionsActionRouteImport } from './routes/api/admin/submissions/action'
import { Route as ApiAdminStoriesVisibilityRouteImport } from './routes/api/admin/stories/visibility'
import { Route as ApiAdminStoriesDuplicateRouteImport } from './routes/api/admin/stories/duplicate'
import { Route as ApiAdminStoriesBulkRouteImport } from './routes/api/admin/stories/bulk'
import { Route as ApiAdminStoriesIdRouteImport } from './routes/api/admin/stories.$id'
import { Route as ApiAdminStatesIdRouteImport } from './routes/api/admin/states.$id'
import { Route as ApiAdminCategoriesIdRouteImport } from './routes/api/admin/categories.$id'
import { Route as ApiAdminAuthorsIdRouteImport } from './routes/api/admin/authors.$id'
import { Route as AdminStoriesIdEditRouteImport } from './routes/admin/stories/$id.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const ApiUserStatsRoute = ApiUserStatsRouteImport.update({
  id: '/api/user-stats',
  path: '/api/user-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendingRoute = ApiTrendingRouteImport.update({
  id: '/api/trending',
  path: '/api/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemesRoute = ApiThemesRouteImport.update({
  id: '/api/themes',
  path: '/api/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesCatalogueDataRoute = ApiStoriesCatalogueDataRouteImport.update({
  id: '/api/stories-catalogue-data',
  path: '/api/stories-catalogue-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesCatalogueRoute = ApiStoriesCatalogueRouteImport.update({
  id: '/api/stories-catalogue',
  path: '/api/stories-catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesRoute = ApiStoriesRouteImport.update({
  id: '/api/stories',
  path: '/api/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatesRoute = ApiStatesRouteImport.update({
  id: '/api/states',
  path: '/api/states',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadingProgressRoute = ApiReadingProgressRouteImport.update({
  id: '/api/reading-progress',
  path: '/api/reading-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLikesRoute = ApiLikesRouteImport.update({
  id: '/api/likes',
  path: '/api/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLatestStoriesRoute = ApiLatestStoriesRouteImport.update({
  id: '/api/latest-stories',
  path: '/api/latest-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeroSlidesRoute = ApiHeroSlidesRouteImport.update({
  id: '/api/hero-slides',
  path: '/api/hero-slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHeroOfTheDayRoute = ApiHeroOfTheDayRouteImport.update({
  id: '/api/hero-of-the-day',
  path: '/api/hero-of-the-day',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeaturedRoute = ApiFeaturedRouteImport.update({
  id: '/api/featured',
  path: '/api/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: '/api/bookmarks',
  path: '/api/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorsRoute = ApiAuthorsRouteImport.update({
  id: '/api/authors',
  path: '/api/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesIndexRoute = AdminStoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatesIndexRoute = AdminStatesIndexRouteImport.update({
  id: '/states/',
  path: '/states/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityIndexRoute = AdminCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthorsIndexRoute = AdminAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiUserStatsMeRoute = ApiUserStatsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiUserStatsRoute,
} as any)
const ApiStoriesSearchRoute = ApiStoriesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiStoriesRecommendedRoute = ApiStoriesRecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiStoriesLatestRoute = ApiStoriesLatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiStoriesFilterRoute = ApiStoriesFilterRouteImport.update({
  id: '/filter',
  path: '/filter',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiStoriesFeaturedRoute = ApiStoriesFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiStoriesSlugRoute = ApiStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiCommentsReportRoute = ApiCommentsReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsLikeRoute = ApiCommentsLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsRoute = ApiAdminSubmissionsRouteImport.update({
  id: '/api/admin/submissions',
  path: '/api/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStoriesRoute = ApiAdminStoriesRouteImport.update({
  id: '/api/admin/stories',
  path: '/api/admin/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatesRoute = ApiAdminStatesRouteImport.update({
  id: '/api/admin/states',
  path: '/api/admin/states',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaRoute = ApiAdminMediaRouteImport.update({
  id: '/api/admin/media',
  path: '/api/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCommentsRoute = ApiAdminCommentsRouteImport.update({
  id: '/api/admin/comments',
  path: '/api/admin/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthorsRoute = ApiAdminAuthorsRouteImport.update({
  id: '/api/admin/authors',
  path: '/api/admin/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnalyticsRoute = ApiAdminAnalyticsRouteImport.update({
  id: '/api/admin/analytics',
  path: '/api/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAchievementsRoute = ApiAdminAchievementsRouteImport.update({
  id: '/api/admin/achievements',
  path: '/api/admin/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoriesNewRoute = AdminStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminSubmissionsActionRoute =
  ApiAdminSubmissionsActionRouteImport.update({
    id: '/action',
    path: '/action',
    getParentRoute: () => ApiAdminSubmissionsRoute,
  } as any)
const ApiAdminStoriesVisibilityRoute =
  ApiAdminStoriesVisibilityRouteImport.update({
    id: '/visibility',
    path: '/visibility',
    getParentRoute: () => ApiAdminStoriesRoute,
  } as any)
const ApiAdminStoriesDuplicateRoute =
  ApiAdminStoriesDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => ApiAdminStoriesRoute,
  } as any)
const ApiAdminStoriesBulkRoute = ApiAdminStoriesBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ApiAdminStoriesRoute,
} as any)
const ApiAdminStoriesIdRoute = ApiAdminStoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminStoriesRoute,
} as any)
const ApiAdminStatesIdRoute = ApiAdminStatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminStatesRoute,
} as any)
const ApiAdminCategoriesIdRoute = ApiAdminCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCategoriesRoute,
} as any)
const ApiAdminAuthorsIdRoute = ApiAdminAuthorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminAuthorsRoute,
} as any)
const AdminStoriesIdEditRoute = AdminStoriesIdEditRouteImport.update({
  id: '/stories/$id/edit',
  path: '/stories/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/api/authors': typeof ApiAuthorsRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/featured': typeof ApiFeaturedRoute
  '/api/hero-of-the-day': typeof ApiHeroOfTheDayRoute
  '/api/hero-slides': typeof ApiHeroSlidesRoute
  '/api/latest-stories': typeof ApiLatestStoriesRoute
  '/api/likes': typeof ApiLikesRoute
  '/api/reading-progress': typeof ApiReadingProgressRoute
  '/api/states': typeof ApiStatesRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/api/stories-catalogue': typeof ApiStoriesCatalogueRoute
  '/api/stories-catalogue-data': typeof ApiStoriesCatalogueDataRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/themes': typeof ApiThemesRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/user-stats': typeof ApiUserStatsRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/api/admin/achievements': typeof ApiAdminAchievementsRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/authors': typeof ApiAdminAuthorsRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/comments': typeof ApiAdminCommentsRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/states': typeof ApiAdminStatesRouteWithChildren
  '/api/admin/stories': typeof ApiAdminStoriesRouteWithChildren
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/comments/like': typeof ApiCommentsLikeRoute
  '/api/comments/report': typeof ApiCommentsReportRoute
  '/api/stories/$slug': typeof ApiStoriesSlugRoute
  '/api/stories/featured': typeof ApiStoriesFeaturedRoute
  '/api/stories/filter': typeof ApiStoriesFilterRoute
  '/api/stories/latest': typeof ApiStoriesLatestRoute
  '/api/stories/recommended': typeof ApiStoriesRecommendedRoute
  '/api/stories/search': typeof ApiStoriesSearchRoute
  '/api/user-stats/me': typeof ApiUserStatsMeRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/authors/': typeof AdminAuthorsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/community/': typeof AdminCommunityIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/states/': typeof AdminStatesIndexRoute
  '/admin/stories/': typeof AdminStoriesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/stories/$id/edit': typeof AdminStoriesIdEditRoute
  '/api/admin/authors/$id': typeof ApiAdminAuthorsIdRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/states/$id': typeof ApiAdminStatesIdRoute
  '/api/admin/stories/$id': typeof ApiAdminStoriesIdRoute
  '/api/admin/stories/bulk': typeof ApiAdminStoriesBulkRoute
  '/api/admin/stories/duplicate': typeof ApiAdminStoriesDuplicateRoute
  '/api/admin/stories/visibility': typeof ApiAdminStoriesVisibilityRoute
  '/api/admin/submissions/action': typeof ApiAdminSubmissionsActionRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/api/authors': typeof ApiAuthorsRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/featured': typeof ApiFeaturedRoute
  '/api/hero-of-the-day': typeof ApiHeroOfTheDayRoute
  '/api/hero-slides': typeof ApiHeroSlidesRoute
  '/api/latest-stories': typeof ApiLatestStoriesRoute
  '/api/likes': typeof ApiLikesRoute
  '/api/reading-progress': typeof ApiReadingProgressRoute
  '/api/states': typeof ApiStatesRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/api/stories-catalogue': typeof ApiStoriesCatalogueRoute
  '/api/stories-catalogue-data': typeof ApiStoriesCatalogueDataRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/themes': typeof ApiThemesRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/user-stats': typeof ApiUserStatsRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/api/admin/achievements': typeof ApiAdminAchievementsRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/authors': typeof ApiAdminAuthorsRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/comments': typeof ApiAdminCommentsRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/states': typeof ApiAdminStatesRouteWithChildren
  '/api/admin/stories': typeof ApiAdminStoriesRouteWithChildren
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/comments/like': typeof ApiCommentsLikeRoute
  '/api/comments/report': typeof ApiCommentsReportRoute
  '/api/stories/$slug': typeof ApiStoriesSlugRoute
  '/api/stories/featured': typeof ApiStoriesFeaturedRoute
  '/api/stories/filter': typeof ApiStoriesFilterRoute
  '/api/stories/latest': typeof ApiStoriesLatestRoute
  '/api/stories/recommended': typeof ApiStoriesRecommendedRoute
  '/api/stories/search': typeof ApiStoriesSearchRoute
  '/api/user-stats/me': typeof ApiUserStatsMeRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/authors': typeof AdminAuthorsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/community': typeof AdminCommunityIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/states': typeof AdminStatesIndexRoute
  '/admin/stories': typeof AdminStoriesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/stories/$id/edit': typeof AdminStoriesIdEditRoute
  '/api/admin/authors/$id': typeof ApiAdminAuthorsIdRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/states/$id': typeof ApiAdminStatesIdRoute
  '/api/admin/stories/$id': typeof ApiAdminStoriesIdRoute
  '/api/admin/stories/bulk': typeof ApiAdminStoriesBulkRoute
  '/api/admin/stories/duplicate': typeof ApiAdminStoriesDuplicateRoute
  '/api/admin/stories/visibility': typeof ApiAdminStoriesVisibilityRoute
  '/api/admin/submissions/action': typeof ApiAdminSubmissionsActionRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/api/authors': typeof ApiAuthorsRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/featured': typeof ApiFeaturedRoute
  '/api/hero-of-the-day': typeof ApiHeroOfTheDayRoute
  '/api/hero-slides': typeof ApiHeroSlidesRoute
  '/api/latest-stories': typeof ApiLatestStoriesRoute
  '/api/likes': typeof ApiLikesRoute
  '/api/reading-progress': typeof ApiReadingProgressRoute
  '/api/states': typeof ApiStatesRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/api/stories-catalogue': typeof ApiStoriesCatalogueRoute
  '/api/stories-catalogue-data': typeof ApiStoriesCatalogueDataRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/api/themes': typeof ApiThemesRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/user-stats': typeof ApiUserStatsRouteWithChildren
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/api/admin/achievements': typeof ApiAdminAchievementsRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/authors': typeof ApiAdminAuthorsRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/comments': typeof ApiAdminCommentsRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/states': typeof ApiAdminStatesRouteWithChildren
  '/api/admin/stories': typeof ApiAdminStoriesRouteWithChildren
  '/api/admin/submissions': typeof ApiAdminSubmissionsRouteWithChildren
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/comments/like': typeof ApiCommentsLikeRoute
  '/api/comments/report': typeof ApiCommentsReportRoute
  '/api/stories/$slug': typeof ApiStoriesSlugRoute
  '/api/stories/featured': typeof ApiStoriesFeaturedRoute
  '/api/stories/filter': typeof ApiStoriesFilterRoute
  '/api/stories/latest': typeof ApiStoriesLatestRoute
  '/api/stories/recommended': typeof ApiStoriesRecommendedRoute
  '/api/stories/search': typeof ApiStoriesSearchRoute
  '/api/user-stats/me': typeof ApiUserStatsMeRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/authors/': typeof AdminAuthorsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/community/': typeof AdminCommunityIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/states/': typeof AdminStatesIndexRoute
  '/admin/stories/': typeof AdminStoriesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/stories/$id/edit': typeof AdminStoriesIdEditRoute
  '/api/admin/authors/$id': typeof ApiAdminAuthorsIdRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/states/$id': typeof ApiAdminStatesIdRoute
  '/api/admin/stories/$id': typeof ApiAdminStoriesIdRoute
  '/api/admin/stories/bulk': typeof ApiAdminStoriesBulkRoute
  '/api/admin/stories/duplicate': typeof ApiAdminStoriesDuplicateRoute
  '/api/admin/stories/visibility': typeof ApiAdminStoriesVisibilityRoute
  '/api/admin/submissions/action': typeof ApiAdminSubmissionsActionRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/explore'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/stories'
    | '/verify-email'
    | '/admin/achievements'
    | '/admin/comments'
    | '/admin/leaderboard'
    | '/api/authors'
    | '/api/bookmarks'
    | '/api/categories'
    | '/api/chat'
    | '/api/comments'
    | '/api/featured'
    | '/api/hero-of-the-day'
    | '/api/hero-slides'
    | '/api/latest-stories'
    | '/api/likes'
    | '/api/reading-progress'
    | '/api/states'
    | '/api/stories'
    | '/api/stories-catalogue'
    | '/api/stories-catalogue-data'
    | '/api/submissions'
    | '/api/themes'
    | '/api/trending'
    | '/api/user-stats'
    | '/stories/$slug'
    | '/admin/'
    | '/stories/'
    | '/admin/stories/new'
    | '/api/admin/achievements'
    | '/api/admin/analytics'
    | '/api/admin/authors'
    | '/api/admin/categories'
    | '/api/admin/comments'
    | '/api/admin/media'
    | '/api/admin/settings'
    | '/api/admin/states'
    | '/api/admin/stories'
    | '/api/admin/submissions'
    | '/api/admin/users'
    | '/api/auth/profile'
    | '/api/comments/like'
    | '/api/comments/report'
    | '/api/stories/$slug'
    | '/api/stories/featured'
    | '/api/stories/filter'
    | '/api/stories/latest'
    | '/api/stories/recommended'
    | '/api/stories/search'
    | '/api/user-stats/me'
    | '/admin/analytics/'
    | '/admin/authors/'
    | '/admin/categories/'
    | '/admin/community/'
    | '/admin/media/'
    | '/admin/settings/'
    | '/admin/states/'
    | '/admin/stories/'
    | '/admin/users/'
    | '/admin/stories/$id/edit'
    | '/api/admin/authors/$id'
    | '/api/admin/categories/$id'
    | '/api/admin/states/$id'
    | '/api/admin/stories/$id'
    | '/api/admin/stories/bulk'
    | '/api/admin/stories/duplicate'
    | '/api/admin/stories/visibility'
    | '/api/admin/submissions/action'
    | '/api/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/explore'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin/achievements'
    | '/admin/comments'
    | '/admin/leaderboard'
    | '/api/authors'
    | '/api/bookmarks'
    | '/api/categories'
    | '/api/chat'
    | '/api/comments'
    | '/api/featured'
    | '/api/hero-of-the-day'
    | '/api/hero-slides'
    | '/api/latest-stories'
    | '/api/likes'
    | '/api/reading-progress'
    | '/api/states'
    | '/api/stories'
    | '/api/stories-catalogue'
    | '/api/stories-catalogue-data'
    | '/api/submissions'
    | '/api/themes'
    | '/api/trending'
    | '/api/user-stats'
    | '/stories/$slug'
    | '/admin'
    | '/stories'
    | '/admin/stories/new'
    | '/api/admin/achievements'
    | '/api/admin/analytics'
    | '/api/admin/authors'
    | '/api/admin/categories'
    | '/api/admin/comments'
    | '/api/admin/media'
    | '/api/admin/settings'
    | '/api/admin/states'
    | '/api/admin/stories'
    | '/api/admin/submissions'
    | '/api/admin/users'
    | '/api/auth/profile'
    | '/api/comments/like'
    | '/api/comments/report'
    | '/api/stories/$slug'
    | '/api/stories/featured'
    | '/api/stories/filter'
    | '/api/stories/latest'
    | '/api/stories/recommended'
    | '/api/stories/search'
    | '/api/user-stats/me'
    | '/admin/analytics'
    | '/admin/authors'
    | '/admin/categories'
    | '/admin/community'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/states'
    | '/admin/stories'
    | '/admin/users'
    | '/admin/stories/$id/edit'
    | '/api/admin/authors/$id'
    | '/api/admin/categories/$id'
    | '/api/admin/states/$id'
    | '/api/admin/stories/$id'
    | '/api/admin/stories/bulk'
    | '/api/admin/stories/duplicate'
    | '/api/admin/stories/visibility'
    | '/api/admin/submissions/action'
    | '/api/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/explore'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/stories'
    | '/verify-email'
    | '/admin/achievements'
    | '/admin/comments'
    | '/admin/leaderboard'
    | '/api/authors'
    | '/api/bookmarks'
    | '/api/categories'
    | '/api/chat'
    | '/api/comments'
    | '/api/featured'
    | '/api/hero-of-the-day'
    | '/api/hero-slides'
    | '/api/latest-stories'
    | '/api/likes'
    | '/api/reading-progress'
    | '/api/states'
    | '/api/stories'
    | '/api/stories-catalogue'
    | '/api/stories-catalogue-data'
    | '/api/submissions'
    | '/api/themes'
    | '/api/trending'
    | '/api/user-stats'
    | '/stories/$slug'
    | '/admin/'
    | '/stories/'
    | '/admin/stories/new'
    | '/api/admin/achievements'
    | '/api/admin/analytics'
    | '/api/admin/authors'
    | '/api/admin/categories'
    | '/api/admin/comments'
    | '/api/admin/media'
    | '/api/admin/settings'
    | '/api/admin/states'
    | '/api/admin/stories'
    | '/api/admin/submissions'
    | '/api/admin/users'
    | '/api/auth/profile'
    | '/api/comments/like'
    | '/api/comments/report'
    | '/api/stories/$slug'
    | '/api/stories/featured'
    | '/api/stories/filter'
    | '/api/stories/latest'
    | '/api/stories/recommended'
    | '/api/stories/search'
    | '/api/user-stats/me'
    | '/admin/analytics/'
    | '/admin/authors/'
    | '/admin/categories/'
    | '/admin/community/'
    | '/admin/media/'
    | '/admin/settings/'
    | '/admin/states/'
    | '/admin/stories/'
    | '/admin/users/'
    | '/admin/stories/$id/edit'
    | '/api/admin/authors/$id'
    | '/api/admin/categories/$id'
    | '/api/admin/states/$id'
    | '/api/admin/stories/$id'
    | '/api/admin/stories/bulk'
    | '/api/admin/stories/duplicate'
    | '/api/admin/stories/visibility'
    | '/api/admin/submissions/action'
    | '/api/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthorsRoute: typeof ApiAuthorsRoute
  ApiBookmarksRoute: typeof ApiBookmarksRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCommentsRoute: typeof ApiCommentsRouteWithChildren
  ApiFeaturedRoute: typeof ApiFeaturedRoute
  ApiHeroOfTheDayRoute: typeof ApiHeroOfTheDayRoute
  ApiHeroSlidesRoute: typeof ApiHeroSlidesRoute
  ApiLatestStoriesRoute: typeof ApiLatestStoriesRoute
  ApiLikesRoute: typeof ApiLikesRoute
  ApiReadingProgressRoute: typeof ApiReadingProgressRoute
  ApiStatesRoute: typeof ApiStatesRoute
  ApiStoriesRoute: typeof ApiStoriesRouteWithChildren
  ApiStoriesCatalogueRoute: typeof ApiStoriesCatalogueRoute
  ApiStoriesCatalogueDataRoute: typeof ApiStoriesCatalogueDataRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
  ApiThemesRoute: typeof ApiThemesRoute
  ApiTrendingRoute: typeof ApiTrendingRoute
  ApiUserStatsRoute: typeof ApiUserStatsRouteWithChildren
  ApiAdminAchievementsRoute: typeof ApiAdminAchievementsRoute
  ApiAdminAnalyticsRoute: typeof ApiAdminAnalyticsRoute
  ApiAdminAuthorsRoute: typeof ApiAdminAuthorsRouteWithChildren
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRouteWithChildren
  ApiAdminCommentsRoute: typeof ApiAdminCommentsRoute
  ApiAdminMediaRoute: typeof ApiAdminMediaRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminStatesRoute: typeof ApiAdminStatesRouteWithChildren
  ApiAdminStoriesRoute: typeof ApiAdminStoriesRouteWithChildren
  ApiAdminSubmissionsRoute: typeof ApiAdminSubmissionsRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/api/user-stats': {
      id: '/api/user-stats'
      path: '/api/user-stats'
      fullPath: '/api/user-stats'
      preLoaderRoute: typeof ApiUserStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trending': {
      id: '/api/trending'
      path: '/api/trending'
      fullPath: '/api/trending'
      preLoaderRoute: typeof ApiTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/themes': {
      id: '/api/themes'
      path: '/api/themes'
      fullPath: '/api/themes'
      preLoaderRoute: typeof ApiThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories-catalogue-data': {
      id: '/api/stories-catalogue-data'
      path: '/api/stories-catalogue-data'
      fullPath: '/api/stories-catalogue-data'
      preLoaderRoute: typeof ApiStoriesCatalogueDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories-catalogue': {
      id: '/api/stories-catalogue'
      path: '/api/stories-catalogue'
      fullPath: '/api/stories-catalogue'
      preLoaderRoute: typeof ApiStoriesCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories': {
      id: '/api/stories'
      path: '/api/stories'
      fullPath: '/api/stories'
      preLoaderRoute: typeof ApiStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/states': {
      id: '/api/states'
      path: '/api/states'
      fullPath: '/api/states'
      preLoaderRoute: typeof ApiStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reading-progress': {
      id: '/api/reading-progress'
      path: '/api/reading-progress'
      fullPath: '/api/reading-progress'
      preLoaderRoute: typeof ApiReadingProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/likes': {
      id: '/api/likes'
      path: '/api/likes'
      fullPath: '/api/likes'
      preLoaderRoute: typeof ApiLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/latest-stories': {
      id: '/api/latest-stories'
      path: '/api/latest-stories'
      fullPath: '/api/latest-stories'
      preLoaderRoute: typeof ApiLatestStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hero-slides': {
      id: '/api/hero-slides'
      path: '/api/hero-slides'
      fullPath: '/api/hero-slides'
      preLoaderRoute: typeof ApiHeroSlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hero-of-the-day': {
      id: '/api/hero-of-the-day'
      path: '/api/hero-of-the-day'
      fullPath: '/api/hero-of-the-day'
      preLoaderRoute: typeof ApiHeroOfTheDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/featured': {
      id: '/api/featured'
      path: '/api/featured'
      fullPath: '/api/featured'
      preLoaderRoute: typeof ApiFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks': {
      id: '/api/bookmarks'
      path: '/api/bookmarks'
      fullPath: '/api/bookmarks'
      preLoaderRoute: typeof ApiBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authors': {
      id: '/api/authors'
      path: '/api/authors'
      fullPath: '/api/authors'
      preLoaderRoute: typeof ApiAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories/': {
      id: '/admin/stories/'
      path: '/stories'
      fullPath: '/admin/stories/'
      preLoaderRoute: typeof AdminStoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/states/': {
      id: '/admin/states/'
      path: '/states'
      fullPath: '/admin/states/'
      preLoaderRoute: typeof AdminStatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community/': {
      id: '/admin/community/'
      path: '/community'
      fullPath: '/admin/community/'
      preLoaderRoute: typeof AdminCommunityIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/authors/': {
      id: '/admin/authors/'
      path: '/authors'
      fullPath: '/admin/authors/'
      preLoaderRoute: typeof AdminAuthorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/user-stats/me': {
      id: '/api/user-stats/me'
      path: '/me'
      fullPath: '/api/user-stats/me'
      preLoaderRoute: typeof ApiUserStatsMeRouteImport
      parentRoute: typeof ApiUserStatsRoute
    }
    '/api/stories/search': {
      id: '/api/stories/search'
      path: '/search'
      fullPath: '/api/stories/search'
      preLoaderRoute: typeof ApiStoriesSearchRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/stories/recommended': {
      id: '/api/stories/recommended'
      path: '/recommended'
      fullPath: '/api/stories/recommended'
      preLoaderRoute: typeof ApiStoriesRecommendedRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/stories/latest': {
      id: '/api/stories/latest'
      path: '/latest'
      fullPath: '/api/stories/latest'
      preLoaderRoute: typeof ApiStoriesLatestRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/stories/filter': {
      id: '/api/stories/filter'
      path: '/filter'
      fullPath: '/api/stories/filter'
      preLoaderRoute: typeof ApiStoriesFilterRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/stories/featured': {
      id: '/api/stories/featured'
      path: '/featured'
      fullPath: '/api/stories/featured'
      preLoaderRoute: typeof ApiStoriesFeaturedRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/stories/$slug': {
      id: '/api/stories/$slug'
      path: '/$slug'
      fullPath: '/api/stories/$slug'
      preLoaderRoute: typeof ApiStoriesSlugRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/comments/report': {
      id: '/api/comments/report'
      path: '/report'
      fullPath: '/api/comments/report'
      preLoaderRoute: typeof ApiCommentsReportRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/like': {
      id: '/api/comments/like'
      path: '/like'
      fullPath: '/api/comments/like'
      preLoaderRoute: typeof ApiCommentsLikeRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions': {
      id: '/api/admin/submissions'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions'
      preLoaderRoute: typeof ApiAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stories': {
      id: '/api/admin/stories'
      path: '/api/admin/stories'
      fullPath: '/api/admin/stories'
      preLoaderRoute: typeof ApiAdminStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/states': {
      id: '/api/admin/states'
      path: '/api/admin/states'
      fullPath: '/api/admin/states'
      preLoaderRoute: typeof ApiAdminStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media': {
      id: '/api/admin/media'
      path: '/api/admin/media'
      fullPath: '/api/admin/media'
      preLoaderRoute: typeof ApiAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/comments': {
      id: '/api/admin/comments'
      path: '/api/admin/comments'
      fullPath: '/api/admin/comments'
      preLoaderRoute: typeof ApiAdminCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/authors': {
      id: '/api/admin/authors'
      path: '/api/admin/authors'
      fullPath: '/api/admin/authors'
      preLoaderRoute: typeof ApiAdminAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/analytics': {
      id: '/api/admin/analytics'
      path: '/api/admin/analytics'
      fullPath: '/api/admin/analytics'
      preLoaderRoute: typeof ApiAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/achievements': {
      id: '/api/admin/achievements'
      path: '/api/admin/achievements'
      fullPath: '/api/admin/achievements'
      preLoaderRoute: typeof ApiAdminAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stories/new': {
      id: '/admin/stories/new'
      path: '/stories/new'
      fullPath: '/admin/stories/new'
      preLoaderRoute: typeof AdminStoriesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/submissions/action': {
      id: '/api/admin/submissions/action'
      path: '/action'
      fullPath: '/api/admin/submissions/action'
      preLoaderRoute: typeof ApiAdminSubmissionsActionRouteImport
      parentRoute: typeof ApiAdminSubmissionsRoute
    }
    '/api/admin/stories/visibility': {
      id: '/api/admin/stories/visibility'
      path: '/visibility'
      fullPath: '/api/admin/stories/visibility'
      preLoaderRoute: typeof ApiAdminStoriesVisibilityRouteImport
      parentRoute: typeof ApiAdminStoriesRoute
    }
    '/api/admin/stories/duplicate': {
      id: '/api/admin/stories/duplicate'
      path: '/duplicate'
      fullPath: '/api/admin/stories/duplicate'
      preLoaderRoute: typeof ApiAdminStoriesDuplicateRouteImport
      parentRoute: typeof ApiAdminStoriesRoute
    }
    '/api/admin/stories/bulk': {
      id: '/api/admin/stories/bulk'
      path: '/bulk'
      fullPath: '/api/admin/stories/bulk'
      preLoaderRoute: typeof ApiAdminStoriesBulkRouteImport
      parentRoute: typeof ApiAdminStoriesRoute
    }
    '/api/admin/stories/$id': {
      id: '/api/admin/stories/$id'
      path: '/$id'
      fullPath: '/api/admin/stories/$id'
      preLoaderRoute: typeof ApiAdminStoriesIdRouteImport
      parentRoute: typeof ApiAdminStoriesRoute
    }
    '/api/admin/states/$id': {
      id: '/api/admin/states/$id'
      path: '/$id'
      fullPath: '/api/admin/states/$id'
      preLoaderRoute: typeof ApiAdminStatesIdRouteImport
      parentRoute: typeof ApiAdminStatesRoute
    }
    '/api/admin/categories/$id': {
      id: '/api/admin/categories/$id'
      path: '/$id'
      fullPath: '/api/admin/categories/$id'
      preLoaderRoute: typeof ApiAdminCategoriesIdRouteImport
      parentRoute: typeof ApiAdminCategoriesRoute
    }
    '/api/admin/authors/$id': {
      id: '/api/admin/authors/$id'
      path: '/$id'
      fullPath: '/api/admin/authors/$id'
      preLoaderRoute: typeof ApiAdminAuthorsIdRouteImport
      parentRoute: typeof ApiAdminAuthorsRoute
    }
    '/admin/stories/$id/edit': {
      id: '/admin/stories/$id/edit'
      path: '/stories/$id/edit'
      fullPath: '/admin/stories/$id/edit'
      preLoaderRoute: typeof AdminStoriesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStoriesNewRoute: typeof AdminStoriesNewRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminAuthorsIndexRoute: typeof AdminAuthorsIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCommunityIndexRoute: typeof AdminCommunityIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminStatesIndexRoute: typeof AdminStatesIndexRoute
  AdminStoriesIndexRoute: typeof AdminStoriesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminStoriesIdEditRoute: typeof AdminStoriesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStoriesNewRoute: AdminStoriesNewRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminAuthorsIndexRoute: AdminAuthorsIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCommunityIndexRoute: AdminCommunityIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminStatesIndexRoute: AdminStatesIndexRoute,
  AdminStoriesIndexRoute: AdminStoriesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminStoriesIdEditRoute: AdminStoriesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface ApiCommentsRouteChildren {
  ApiCommentsLikeRoute: typeof ApiCommentsLikeRoute
  ApiCommentsReportRoute: typeof ApiCommentsReportRoute
}

const ApiCommentsRouteChildren: ApiCommentsRouteChildren = {
  ApiCommentsLikeRoute: ApiCommentsLikeRoute,
  ApiCommentsReportRoute: ApiCommentsReportRoute,
}

const ApiCommentsRouteWithChildren = ApiCommentsRoute._addFileChildren(
  ApiCommentsRouteChildren,
)

interface ApiStoriesRouteChildren {
  ApiStoriesSlugRoute: typeof ApiStoriesSlugRoute
  ApiStoriesFeaturedRoute: typeof ApiStoriesFeaturedRoute
  ApiStoriesFilterRoute: typeof ApiStoriesFilterRoute
  ApiStoriesLatestRoute: typeof ApiStoriesLatestRoute
  ApiStoriesRecommendedRoute: typeof ApiStoriesRecommendedRoute
  ApiStoriesSearchRoute: typeof ApiStoriesSearchRoute
}

const ApiStoriesRouteChildren: ApiStoriesRouteChildren = {
  ApiStoriesSlugRoute: ApiStoriesSlugRoute,
  ApiStoriesFeaturedRoute: ApiStoriesFeaturedRoute,
  ApiStoriesFilterRoute: ApiStoriesFilterRoute,
  ApiStoriesLatestRoute: ApiStoriesLatestRoute,
  ApiStoriesRecommendedRoute: ApiStoriesRecommendedRoute,
  ApiStoriesSearchRoute: ApiStoriesSearchRoute,
}

const ApiStoriesRouteWithChildren = ApiStoriesRoute._addFileChildren(
  ApiStoriesRouteChildren,
)

interface ApiUserStatsRouteChildren {
  ApiUserStatsMeRoute: typeof ApiUserStatsMeRoute
}

const ApiUserStatsRouteChildren: ApiUserStatsRouteChildren = {
  ApiUserStatsMeRoute: ApiUserStatsMeRoute,
}

const ApiUserStatsRouteWithChildren = ApiUserStatsRoute._addFileChildren(
  ApiUserStatsRouteChildren,
)

interface ApiAdminAuthorsRouteChildren {
  ApiAdminAuthorsIdRoute: typeof ApiAdminAuthorsIdRoute
}

const ApiAdminAuthorsRouteChildren: ApiAdminAuthorsRouteChildren = {
  ApiAdminAuthorsIdRoute: ApiAdminAuthorsIdRoute,
}

const ApiAdminAuthorsRouteWithChildren = ApiAdminAuthorsRoute._addFileChildren(
  ApiAdminAuthorsRouteChildren,
)

interface ApiAdminCategoriesRouteChildren {
  ApiAdminCategoriesIdRoute: typeof ApiAdminCategoriesIdRoute
}

const ApiAdminCategoriesRouteChildren: ApiAdminCategoriesRouteChildren = {
  ApiAdminCategoriesIdRoute: ApiAdminCategoriesIdRoute,
}

const ApiAdminCategoriesRouteWithChildren =
  ApiAdminCategoriesRoute._addFileChildren(ApiAdminCategoriesRouteChildren)

interface ApiAdminStatesRouteChildren {
  ApiAdminStatesIdRoute: typeof ApiAdminStatesIdRoute
}

const ApiAdminStatesRouteChildren: ApiAdminStatesRouteChildren = {
  ApiAdminStatesIdRoute: ApiAdminStatesIdRoute,
}

const ApiAdminStatesRouteWithChildren = ApiAdminStatesRoute._addFileChildren(
  ApiAdminStatesRouteChildren,
)

interface ApiAdminStoriesRouteChildren {
  ApiAdminStoriesIdRoute: typeof ApiAdminStoriesIdRoute
  ApiAdminStoriesBulkRoute: typeof ApiAdminStoriesBulkRoute
  ApiAdminStoriesDuplicateRoute: typeof ApiAdminStoriesDuplicateRoute
  ApiAdminStoriesVisibilityRoute: typeof ApiAdminStoriesVisibilityRoute
}

const ApiAdminStoriesRouteChildren: ApiAdminStoriesRouteChildren = {
  ApiAdminStoriesIdRoute: ApiAdminStoriesIdRoute,
  ApiAdminStoriesBulkRoute: ApiAdminStoriesBulkRoute,
  ApiAdminStoriesDuplicateRoute: ApiAdminStoriesDuplicateRoute,
  ApiAdminStoriesVisibilityRoute: ApiAdminStoriesVisibilityRoute,
}

const ApiAdminStoriesRouteWithChildren = ApiAdminStoriesRoute._addFileChildren(
  ApiAdminStoriesRouteChildren,
)

interface ApiAdminSubmissionsRouteChildren {
  ApiAdminSubmissionsActionRoute: typeof ApiAdminSubmissionsActionRoute
}

const ApiAdminSubmissionsRouteChildren: ApiAdminSubmissionsRouteChildren = {
  ApiAdminSubmissionsActionRoute: ApiAdminSubmissionsActionRoute,
}

const ApiAdminSubmissionsRouteWithChildren =
  ApiAdminSubmissionsRoute._addFileChildren(ApiAdminSubmissionsRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthorsRoute: ApiAuthorsRoute,
  ApiBookmarksRoute: ApiBookmarksRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCommentsRoute: ApiCommentsRouteWithChildren,
  ApiFeaturedRoute: ApiFeaturedRoute,
  ApiHeroOfTheDayRoute: ApiHeroOfTheDayRoute,
  ApiHeroSlidesRoute: ApiHeroSlidesRoute,
  ApiLatestStoriesRoute: ApiLatestStoriesRoute,
  ApiLikesRoute: ApiLikesRoute,
  ApiReadingProgressRoute: ApiReadingProgressRoute,
  ApiStatesRoute: ApiStatesRoute,
  ApiStoriesRoute: ApiStoriesRouteWithChildren,
  ApiStoriesCatalogueRoute: ApiStoriesCatalogueRoute,
  ApiStoriesCatalogueDataRoute: ApiStoriesCatalogueDataRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
  ApiThemesRoute: ApiThemesRoute,
  ApiTrendingRoute: ApiTrendingRoute,
  ApiUserStatsRoute: ApiUserStatsRouteWithChildren,
  ApiAdminAchievementsRoute: ApiAdminAchievementsRoute,
  ApiAdminAnalyticsRoute: ApiAdminAnalyticsRoute,
  ApiAdminAuthorsRoute: ApiAdminAuthorsRouteWithChildren,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRouteWithChildren,
  ApiAdminCommentsRoute: ApiAdminCommentsRoute,
  ApiAdminMediaRoute: ApiAdminMediaRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminStatesRoute: ApiAdminStatesRouteWithChildren,
  ApiAdminStoriesRoute: ApiAdminStoriesRouteWithChildren,
  ApiAdminSubmissionsRoute: ApiAdminSubmissionsRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
